version: '2'
services:
  db:
    image: mdillon/postgis
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis