apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapwarper-fileserver-claim
spec:
  # storageClassName: manual
  # storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G