apiVersion: v1
kind: PersistentVolume
metadata:
  name: mapwarper-fileserver
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    # change this with the name and internal IP address of the NFS server
    # path: /mapfileshare
    # server: 10.xx.xx.xx
    # You can use envsubst to set the image
    # e.g. FS_PATH=mapfileshare FS_SERVER=10.01.01.01 envsubst < file.yaml
    path: ${FS_PATH}
    server: ${FS_SERVER}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapwarper-fileserver-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T
