apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mapwarper-web
  labels:
    app: web
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: web
    spec:
      # This section describes the containers that make up the deployment
      containers:
        - name: web
          # image: localhost:32000/mapwarper_web:latest
          # You can use envsubst to set the image
          # e.g. IMAGE=localhost:32000/mapwarper_web:latest envsubst < file.yaml 
          image: ${IMAGE}
          imagePullPolicy: Always
          command: ["/bin/bash"]
          args: ["-c", "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 250m
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: mapwarper-filestore-volume
              mountPath: /mnt/mapwarper/maps
              subPath: maps
            - name: mapwarper-filestore-volume
              mountPath: /app/public/shared
              subPath: shared
            - name: bucket-secrets-volume
              mountPath: /secrets/service-account
              readOnly: true

          # set variables from config map from mapwarper-app-config.yml
          envFrom:
            - configMapRef:
                name: mapwarper-app-config
          # Set env variables explicity and secrets from mapwarper-secrets.yml
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mapwarper-secrets
                  key: dbusername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mapwarper-secrets
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mapwarper-secrets
                  key: dbname
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mapwarper-secrets
                  key: secret-key-base
            # set env manually
            - name: RAILS_ENV
              value: "production"
            - name: RACK_ENV
              value: "production"
            # comment out RAILS_SERVE_STATIC_FILES if you want to disable this setting, rather than change the value. Uncomment for use with Puma in production 
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"


        # Uncomment to use proxy in local env for example or where a private ip isnt set up
        # - name: cloudsql-proxy
        #   image: gcr.io/cloudsql-docker/gce-proxy:1.11
        #   env:
        #     - name: DB_INSTANCE
        #       valueFrom:
        #         secretKeyRef:
        #           name: mapwarper-secrets
        #           key:  dbinstance
        #   command: ["/cloud_sql_proxy"]
        #   args: ["-instances=$(DB_INSTANCE)=tcp:5432", "-credential_file=/secrets/cloudsql/secret_cloud_sql.json"]
        #   volumeMounts:
        #     - name: sql-secrets-volume
        #       mountPath: /secrets/cloudsql
        #       readOnly: true
        #   resources:
        #     limits:
        #       cpu: 1
        #     requests:
        #       cpu: 250m

      volumes:
        - name: mapwarper-filestore-volume
          persistentVolumeClaim:
            claimName: mapwarper-fileserver-claim
            readOnly: false
        - name: sql-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
        - name: bucket-secrets-volume
          secret:
            secretName: bucket-credentials



