defaults: &defaults
  email: example_user@example.com
  addthis_twitter_user: example_user@example.com
  addthis_user: example_user
  google_analytics_code:
  google_analytics_cookie_path:  ""
  src_maps_dir: 
  dst_maps_dir: 
  map_mask_dir: 
  tileindex_dir: 
  mapzen_key: "ABC"
  geocode_country: ""
  geoparse_geocodexyz_key: ""
  geoparse_region: ""
  geoparse_enable: false
  host: "localhost:3000"
  site_name: "MapWarper"
  host_with_scheme: "http://localhost:3000"
  full_site_name: "MapWarper.net"
  reply_to: "example@example.com"
  omniauth_osm_key: "ABC"
  omniauth_osm_secret: "ABC"
  omniauth_twitter_key: "ABC"
  omniauth_twitter_secret: "ABC"
  omniauth_mediawiki_site: "https://commons.wikimedia.org"
  omniauth_mediawiki_key: "ABC"
  omniauth_mediawiki_secret: "ABC"
  omniauth_github_key: "ABC"
  omniauth_github_secret: "ABC"
  omniauth_facebook_key: "ABC"
  omniauth_facebook_secret: "ABC"
  omniauth_google_key: ""
  omniauth_google_secret: ""
  id_key: ""
  id_secret: ""
  mapbox_access_token: ""
  localeapp_api_key: ""
  import_maps_sftp_path: "/home/sftpuser/maps"
  #gdal_path: "/home/fwtools/bin_safe/"
  gdal_path: ""
  gdal_memory_limit: ""
  disabled_site: false
  google_storage_enabled: false
  google_json_key_location: ""
  google_storage_project: ""
  google_storage_bucket: ""
  public_shared_dir: ""  #used when saving to a shared directory (e.g. shared_uploads_dir: "shared" for RAILS_ROOT/public/shared/ which can be mounted as a volume via k8s ) 
  debug_k8s: false
  google_maps_key: ""
  sendgrid_api_key: ""
  nypl_repo_token: ""
  enable_throttling: "false"  #should be a string not boolean
  throttle_limit: 30
  throttle_period: 60
  throttle_safelist_ips: #"127.0.0.1,192.168.0.1" #comma separated
  google_tiles_bucket: ""
  cdn_tiles_host:  ""  #e.g. https://tiles.example.com
  smtp_address: 
  smtp_port:
  smtp_username:
  smtp_password:
  enable_ocr_job: "true"  #set to "false" to disable the OCR and geocoding job upon map creation
  

development:
  <<: *defaults

test:
  <<: *defaults
  email: test_user@example.com

production:
  <<: *defaults
  email: production_user@example.com
  src_maps_dir: "/var/etc/maps/src/"
  dst_maps_dir: "/var/etc/maps/dst/"
