development:
  adapter: postgis
  database: mapwarper_development
  host: localhost
  username: postgres
  password:
  pool: 5

test:
  adapter: postgis
  database: mapwarper_test
  pool: 5
  timeout: 5000

# If using Docker Compose for testing
# comment the above test section and uncomment the following definitions 
#
# test:
#   adapter: postgis
#   database: mapwarper_test
#   host: localhost
#   username: postgres
#   password:
#   pool: 5

production:
  adapter: postgis
  # database: mapwarper_production
  # host: localhost
  # pool: 5 
  # timeout: 5000
  # #
  # # below for K8s etc
  # #
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>
  pool: 5 
  timeout: 5000

